# Generated by Django 4.0.4 on 2022-05-28 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_pictures_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='loc',
            new_name='locate',
        ),
    ]
